import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import {Header} from "@/components/header";
import {BottomNavWrapper} from "@/components/bottom-nav-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
        <body className="h-full flex flex-col overflow-hidden">
        <Header />
        <main className="flex-1 overflow-y-auto min-h-0">
            {children}
        </main>
        <BottomNavWrapper />
        <Toaster />
        </body>
        </html>
    );
}
